sudo: required
dist: bionic
language: java
jdk:
  - oraclejdk11
python:
  - "3.6"
services: docker
before_install:
    - sudo apt-get update
    - cd /ApiRestSpringBootDockerMain/ApiRestSpringBootDocker
    - mvn clean package
    - cd ..
script:
    - docker-compose build
before_deploy:
    - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
    provider: script
    script: 
       docker tag api-rest-spring-boot:latest andlucsil/api-rest-spring-boot:$TRAVIS_JOB_ID
       docker push andlucsil/api-rest-spring-boot;
    on:
      branch: master
after_success:
    - sudo apt-get -y install python3-pip python-dev
    - sudo pip3 install -U setuptools
    - sudo pip3 install -U virtualenvwrapper
    - python3 -V
    - pip3 -V
    - pip3 uninstall wheel
    - pip3 install wheel
    - pip3 install awscli --upgrade --user
    - export PATH=$PATH:$HOME/.local/bin
    - eval $(aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 512551382194.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/rest-spring-boot)
    - docker tag rest-spring-boot:latest $IMAGE_REPO_URL:$TRAVIS_JOB_ID
    - docker push 512551382194.dkr.ecr.sa-east-1.amazonaws.com/rest-spring-boot:$TRAVIS_JOB_ID
    - add-apt-repository ppa:eugenesan/ppa
    - apt-get update
    - apt-get install jq -y
    - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee -a /usr/bin/ecs-deploy
    - sudo chmod +x /usr/bin/ecs-deploy
    - echo "AWS ECS-Deploy Setup is Configured!"
    - ecs-deploy -c $CLUSTER_NAME -n $SERVICE_NAME -i $IMAGE_REPO_URL:$TRAVIS_JOB_ID -r $AWS_DEFAULT_REGION -t 240
notifications:
    email: true
