language: bash
services: docker
script:
    - docker-compose build
before_deploy:
    - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
    provider: script
    script: 
       docker push andlucsil/api-rest-spring-boot;
       docker push andlucsil/mysql-api-rest-spring-boot;
    on:
      branch: master
notifications:
    email: true
